weixin
  dubbo
    reistry
      address=120.27.53.171:2181
      protocol=zookeeper
    host
      address=10.10.51.45
    admin
      service
        port=20881
    redis
      service
        port=20882
    cart
      service
        port=20883
    item
      service
        port=20884
    system
      service
        port=20885
    user
      service
        port=20886
    message
      service
        port=20887
    rabbitmq
      service
        port=20888
    comment
      service
        port=20889
    order
      service
        port=20890
    log
      service
        port=20891
    promotion
      service
        port=20892
